# patch-traefik.yaml
spec:
  template:
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - tail -n+1 -F /data/access.log
        image: busybox
        imagePullPolicy: Always
        name: stream-accesslog
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data