---
# Full configuration available at : https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml

# Logs
# https://docs.traefik.io/observability/logs/
logs:
  # Traefik logs concern everything that happens to Traefik itself (startup, configuration, events, shutdown, and so on).
  general:
    # By default, the logs use a text format (common), but you can
    # also ask for the json format in the format option
    # format: json
    # By default, the level is set to ERROR. Alternative logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
    level: ERROR
  access:
    # To enable access logs
    enabled: true

# Additional arguments to be passed at Traefik's binary
# All available options available on https://docs.traefik.io/reference/static-configuration/cli/
additionalArguments:
  - "--accesslog.filepath=/var/log/traefik/access.log"

# Configure ports
ports:
  # Dashboard (do not expose in production)
  traefik:
    port: 9000
    expose: true
    exposedPort: 9000
    protocol: TCP