# persistence:
#   enabled: true

logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.enabled: false
    pipeline.ecs_compatibility: disabled
logstashPipeline:
  logstash.conf: |
    input {
      beats {
          port => "5044"
      }
    }
    filter {
      # Drop useless events
      if [message] =~ /GET \/healthz HTTP\/1\.1/ {
        drop {}
      }
      else if [message] =~ /GET \/metrics HTTP\/1\.1 / {
        drop {}
      }
      else if [message] =~ /GET \/ping HTTP\/1\.1 / {
        drop {}
      }
    }
    output {
      if [@metadata][beat] == "filebeat" and [event][module] == "traefik" and [project][name] == "apigw"  {
        elasticsearch {
          hosts => ["http://elasticsearch-master:9200"]
          manage_template => false
          index => "traefik"
          pipeline => "%{[@metadata][pipeline]}" 
        }
      } else {
        elasticsearch {
          hosts => ["http://elasticsearch-master:9200"]
          index => "logstash"
        }
      }
      stdout {}
    }

# Custom ports for beats
extraPorts:
  - name: beats
    containerPort: 5044

service:
 type: ClusterIP
 ports:
   - name: beats
     port: 5044
     protocol: TCP
     targetPort: 5044