# persistence:
#   enabled: true

logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.enabled: false
    pipeline.ecs_compatibility: disabled
logstashPipeline:
  logstash.conf: |
    input {
      beats {
          port => "5044"
      }
    }

    filter {

      # Drop useless events
      if [message] =~ /ping/ {
        drop {}
      }

      json {
        id => "json-traefik"
        source => "message"
        target => "app"
        skip_on_invalid_json => "true"
      }

      mutate {
        rename => {
          "[app][ServiceName]" => "traefikService"
          "[app][DownstreamStatus]" => "frontendStatusCode"
          "[app][OriginStatus]" => "backendStatusCode"
        }
      }

      prune {
        blacklist_names => [ "app" ]
      }

    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch-master:9200"]
        pipeline => "%{[@metadata][pipeline]}"
        index => "logstash"
      }
      # Additionnal output for debug purposes
      stdout {}
    }

# Custom ports for beats
extraPorts:
  - name: beats
    containerPort: 5044

# Custom service for beats input
service:
  type: ClusterIP
  ports:
    - name: beats
      port: 5044
      protocol: TCP
      targetPort: 5044